### ISSUE TITLE
Cannot turn off tips

### ISSUE THREAD

**Issue by ghost** [oqyh/Simple-Tips-Chat#1]
Really great plugin. I have been looking for something that would allow me to disable hints on the client side.
However, when I type !tip, I get the following and cannot turn tips on or off
![Counter-strike  Global Offensive Screenshot 2022 08 18 - 23 02 14 99](https://user-images.githubusercontent.com/105159910/185414755-67a76553-1100-4179-90ec-7db98e3076e2.png)
.
I have kz, bhop, surf, and FFA servers and have tried this plugin on all of them with the same results.

**Comment by oqyh** [comment]
after enable it 
plugin will follow 
sm_tips_time "101.0" <--- Time in seconds between Tips Messages
so you need to wait 101.0 sec to show message
![Screenshot (145)](https://user-images.githubusercontent.com/48490385/185492046-13705cec-1351-4493-bc11-c9e8513f623b.png)

**Comment by ghost** [comment]
Thanks for the reply.
This was the case in 1.0.0 in my environment, but it's fixed in 1.0.1!
https://user-images.githubusercontent.com/105159910/185540129-497038d2-311a-49ac-b821-28baa3725b5e.mp4

Thank you very much.
