### ISSUE TITLE
Still can't turn off tips.

### ISSUE THREAD

**Issue by ghost** [oqyh/Simple-Tips-Chat#2]
Sorry for the repetition.
When I type !tip I get a lot of enable and disable output and I can't turn off tip.

https://user-images.githubusercontent.com/105159910/185710351-65a8f7de-2984-4ea1-920c-3add68c890d9.mp4

**Comment by oqyh** [comment]
hello vSxLc,
- when it happen?
- can you send me your Simple_Tips_Chat.cfg 
- can you send me your Simple_Tips_Chat.phrases.txt

**Comment by ghost** [comment]
Thanks for the reply.
This happens when I type !tip
[Simple_Tips_Chat.cfg.txt](https://github.com/oqyh/Simple-Tips-Chat/files/9385795/Simple_Tips_Chat.cfg.txt)

[Simple_Tips_Chat.phrases.txt](https://github.com/oqyh/Simple-Tips-Chat/files/9385794/Simple_Tips_Chat.phrases.txt)

**Comment by oqyh** [comment]
when it happen when map change or too many clients connect?

**Comment by oqyh** [comment]
here 1.0.2 try it and give me feed back 
thanks !
[Simple Tips Chat (1.0.2).zip](https://github.com/oqyh/Simple-Tips-Chat/files/9385833/Simple.Tips.Chat.1.0.2.zip)

**Comment by ghost** [comment]
The amount of output has been reduced, but I still can't turn off tips.
https://user-images.githubusercontent.com/105159910/185720310-afa3c3d4-9bf4-40c5-a999-205523a8a25d.mp4

**Comment by oqyh** [comment]
[new.zip](https://github.com/oqyh/Simple-Tips-Chat/files/9385887/new.zip)
now?

**Comment by ghost** [comment]
Oddly enough, the plugin works immediately after installation but not after changing the map. (Same result)

**Comment by oqyh** [comment]
ok thanks ill take note

**Comment by oqyh** [comment]
please can you type sm plugins list and check if there is any dublicate Simple Tips Chat

**Comment by ghost** [comment]
Doesn't appear to be a duplicate...
[plugins.txt](https://github.com/oqyh/Simple-Tips-Chat/files/9385958/plugins.txt)

**Comment by oqyh** [comment]
updated 1.0.2 fixed the problem thanks for feed back

**Comment by ghost** [comment]
It's fixed!
Thank you for your time!
