### ISSUE TITLE
Changing the map resets tips off

### ISSUE THREAD

**Issue by ghost** [oqyh/Simple-Tips-Chat#3]
When the map is changed, tips will be turned on again

**Comment by oqyh** [comment]
ya thats normal 
would you like me to add cookies to save  toggle 
even if you disconnect

**Comment by ghost** [comment]
Can you please do that for me?

**Comment by oqyh** [comment]
updated 1.0.3
added new cvar 

// Save Enable Disable Client Cookie || 1= Yes || 0= No (Next Map Or Reconnect Client Tips Will Be By Default Enable)
sm_tips_cookie "1"

**Comment by ghost** [comment]
Truly a perfect plugin!
Thanks for your time!
